backend:
  name: github
  branch: master
  repo: lamencha/problog

media_folder: static/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Title', name: 'title' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { name: crop, label: Cream of the Crop 1 to add 0 to omit, widget: number, valueType: int}
      - { label: 'Rate', name: 'rate', widget: 'image' }